# Generated by Django 4.2 on 2023-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_classes_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(default='null')),
                ('distance', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sword_img',
            name='description',
            field=models.TextField(default='null'),
        ),
    ]
