# Generated by Django 4.2 on 2023-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_year_delete_project_classes_class_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='title',
            field=models.CharField(default='year', max_length=4),
        ),
    ]
