# Generated by Django 4.2 on 2023-07-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_sword_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sword_sales',
            name='title',
            field=models.IntegerField(),
        ),
    ]
