# Generated by Django 4.2 on 2023-07-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_sword_sales_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sword_sales',
            name='title',
        ),
        migrations.AddField(
            model_name='sword_sales',
            name='item_number',
            field=models.IntegerField(default=0),
        ),
    ]
