# Generated by Django 4.2 on 2023-10-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_sword_sales_title_sword_sales_item_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sword_img',
            name='title',
        ),
        migrations.AddField(
            model_name='sword_img',
            name='item_number',
            field=models.IntegerField(default=0),
        ),
    ]
