# Generated by Django 4.2 on 2023-10-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_sword_img_title_sword_img_item_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default='null'),
        ),
    ]
