# Generated by Django 4.2 on 2023-10-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_blog_title_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default='yyyy-mm-dd'),
        ),
    ]
