# Generated by Django 4.2 on 2023-10-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default='2023-13-23'),
        ),
    ]
