# Generated by Django 4.2 on 2023-10-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_blog_date_alter_classes_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(),
        ),
    ]
