# Generated by Django 4.2 on 2023-10-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_classes_end_date_alter_classes_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(blank=True, to='projects.blogimages'),
        ),
    ]
