# Generated by Django 4.2 on 2023-11-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_blogimages_remove_blog_images_blog_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sword_img',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sword_sales',
            old_name='images',
            new_name='image',
        ),
    ]
