# Generated by Django 3.2.12 on 2024-03-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_rename_images_sword_img_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='sword_img',
            name='image',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='sword_sales',
            name='image',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
