# Generated by Django 3.2.12 on 2024-03-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
